// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v_1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _classesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listclassesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roll_callsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rollcallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _solverollcallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getclassrosterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _students0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listallstudentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletestudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _classes0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _enrollmentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removestudentfromclassMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importclassdataMw() []app.HandlerFunc {
	// your code...
	return nil
}
