// Code generated by hertz generator.

package main

import (
	"log"

	"FZUSENekoCaller/biz/dal/mysql"
	"FZUSENekoCaller/biz/router"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	if mysql.Init() == nil {
		log.Fatal("mysql initialization failed")
	}

	h := server.Default()

	router.GeneratedRegister(h)
	h.Spin()
}
