// Code generated by hertz generator.

package main

import (
	"log"

	"FZUSENekoCaller/biz/dal/mysql"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// 初始化数据库
	mysql.Init()
	log.Println("数据库初始化成功")

	h := server.Default()

	register(h)

	log.Println("服务器启动在端口 :8888")
	h.Spin()
}
