// Code generated by hertz generator.

package api

import (
	"context"

	api "FZUSENekoCaller/biz/model/api"
	common "FZUSENekoCaller/biz/model/common"
	"FZUSENekoCaller/biz/service"
	"FZUSENekoCaller/pkg/constants"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ImportClassData .
// @router /v1/import/class-data [POST]
func ImportClassData(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ImportDataRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewImportService(ctx)
	if err := s.ImportClassData(&req); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "导入成功"

	c.JSON(consts.StatusOK, resp)
}

// GetClass .
// @router /v1/classes/:class_id [GET]
func GetClass(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.Class)

	s := service.NewAPIService(ctx)
	class, err := s.GetClass(req)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = class

	c.JSON(consts.StatusOK, resp)
}

// ListClasses .
// @router /v1/classes [GET]
func ListClasses(ctx context.Context, c *app.RequestContext) {
	var err error

	resp := new([]*common.Class)

	s := service.NewAPIService(ctx)
	classes, err := s.ListClasses()
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &classes

	c.JSON(consts.StatusOK, resp)
}

// DeleteClass .
// @router /v1/classes/:class_id [DELETE]
func DeleteClass(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetStudent .
// @router /v-1/students/:student_id [GET]
func GetStudent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.Student)

	s := service.NewAPIService(ctx)
	student, err := s.GetStudent(req)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = student

	c.JSON(consts.StatusOK, resp)
}

// ListAllStudents .
// @router /v1/students [GET]
func ListAllStudents(ctx context.Context, c *app.RequestContext) {
	var err error

	resp := new([]*common.Student)

	s := service.NewAPIService(ctx)
	students, err := s.ListAllStudents()
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &students

	c.JSON(consts.StatusOK, resp)
}

// DeleteStudent .
// @router /v1/students/:student_id [DELETE]
func DeleteStudent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetClassRoster .
// @router /v1/roster [GET]
func GetClassRoster(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new([]*common.RosterItem)

	s := service.NewAPIService(ctx)
	roster, err := s.GetClassRoster(req)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &roster

	c.JSON(consts.StatusOK, resp)
}

// RemoveStudentFromClass .
// @router /v1/enrollments/:enrollment_id [DELETE]
func RemoveStudentFromClass(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// RollCall .
// @router /v1/roll-calls [POST]
func RollCall(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RollCallRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RollCallResponse)

	s := service.NewAPIService(ctx)
	currentRoster, err := s.RollCall(&req)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.BaseResponse.Code = constants.CodeSuccess
	resp.BaseResponse.Message = "点名成功"
	resp.RosterItem = &currentRoster

	c.JSON(consts.StatusOK, resp)
}

// SolveRollCall .
// @router /v1/roll-calls/solve [POST]
func SolveRollCall(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SolveRollCallRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}
