// Code generated by hertz generator.

package api

import (
	"context"
	"strconv"

	"FZUSENekoCaller/biz/model/api"
	"FZUSENekoCaller/biz/model/common"
	"FZUSENekoCaller/biz/service"
	"FZUSENekoCaller/pkg/constants"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ImportClassData .
// @router /v1/import/class-data [POST]
func ImportClassData(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ImportDataRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewImportService(ctx)
	if err := s.ImportClassData(&req); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "导入成功"

	c.JSON(consts.StatusOK, resp)
}

// GetClass .
// @router /v1/classes/:class_id [GET]
func GetClass(ctx context.Context, c *app.RequestContext) {
	classID := c.Param("class_id")
	if classID == "" {
		c.String(consts.StatusBadRequest, "class_id is required")
		return
	}

	resp := new(common.Class)

	s := service.NewAPIService(ctx)
	class, err := s.GetClass(classID)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = class

	c.JSON(consts.StatusOK, resp)
}

// ListClasses .
// @router /v1/classes [GET]
func ListClasses(ctx context.Context, c *app.RequestContext) {
	var err error

	resp := new([]*common.Class)

	s := service.NewAPIService(ctx)
	classes, err := s.ListClasses()
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &classes

	c.JSON(consts.StatusOK, resp)
}

// DeleteClass .
// @router /v1/classes/:class_id [DELETE]
func DeleteClass(ctx context.Context, c *app.RequestContext) {
	classID := c.Param("class_id")
	if classID == "" {
		c.String(consts.StatusBadRequest, "class_id is required")
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewAPIService(ctx)
	if err := s.DeleteClass(classID); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "删除班级成功"

	c.JSON(consts.StatusOK, resp)
}

// GetLeaderboard .
// @router /v1/classes/:class_id/leaderboard [GET]
func GetLeaderboard(ctx context.Context, c *app.RequestContext) {
	classID := c.Param("class_id")
	if classID == "" {
		c.String(consts.StatusBadRequest, "class_id is required")
		return
	}

	// 获取top参数，默认10
	topStr := c.Query("top")
	top := 10
	if topStr != "" {
		if t, err := strconv.Atoi(topStr); err == nil && t > 0 {
			top = t
		}
	}

	s := service.NewAPIService(ctx)
	leaderboard, err := s.GetLeaderboard(classID, top)
	if err != nil {
		resp := &common.BaseResponse{
			Code:    constants.CodeFailed,
			Message: err.Error(),
		}
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	c.JSON(consts.StatusOK, leaderboard)
}

// GetClassStats .
// @router /v1/classes/:class_id/stats [GET]
func GetClassStats(ctx context.Context, c *app.RequestContext) {
	classID := c.Param("class_id")
	if classID == "" {
		c.String(consts.StatusBadRequest, "class_id is required")
		return
	}

	s := service.NewAPIService(ctx)
	stats, err := s.GetClassStats(classID)
	if err != nil {
		resp := &common.BaseResponse{
			Code:    constants.CodeFailed,
			Message: err.Error(),
		}
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	c.JSON(consts.StatusOK, stats)
}

// GetStudent .
// @router /v1/students/:student_id [GET]
func GetStudent(ctx context.Context, c *app.RequestContext) {
	studentID := c.Param("student_id")
	if studentID == "" {
		c.String(consts.StatusBadRequest, "student_id is required")
		return
	}

	resp := new(common.Student)

	s := service.NewAPIService(ctx)
	student, err := s.GetStudent(studentID)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = student

	c.JSON(consts.StatusOK, resp)
}

// ListAllStudents .
// @router /v1/students [GET]
func ListAllStudents(ctx context.Context, c *app.RequestContext) {
	var err error

	resp := new([]*common.Student)

	s := service.NewAPIService(ctx)
	students, err := s.ListAllStudents()
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &students

	c.JSON(consts.StatusOK, resp)
}

// DeleteStudent .
// @router /v1/students/:student_id [DELETE]
func DeleteStudent(ctx context.Context, c *app.RequestContext) {
	studentID := c.Param("student_id")
	if studentID == "" {
		c.String(consts.StatusBadRequest, "student_id is required")
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewAPIService(ctx)
	if err := s.DeleteStudent(studentID); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "删除学生成功"

	c.JSON(consts.StatusOK, resp)
}

// GetClassRoster .
// @router /v1/roster [GET]
func GetClassRoster(ctx context.Context, c *app.RequestContext) {
	classID := c.Query("class_id")
	if classID == "" {
		c.String(consts.StatusBadRequest, "class_id is required")
		return
	}

	resp := new([]*common.RosterItem)

	s := service.NewAPIService(ctx)
	roster, err := s.GetClassRoster(classID)
	if err != nil {
		resp = nil
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &roster

	c.JSON(consts.StatusOK, resp)
}

// RemoveStudentFromClass .
// @router /v1/enrollments/:enrollment_id [DELETE]
func RemoveStudentFromClass(ctx context.Context, c *app.RequestContext) {
	enrollmentID := c.Param("enrollment_id")
	if enrollmentID == "" {
		c.String(consts.StatusBadRequest, "enrollment_id is required")
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewAPIService(ctx)
	if err := s.RemoveStudentFromClass(enrollmentID); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "移除学生成功"

	c.JSON(consts.StatusOK, resp)
}

// RollCall .
// @router /v1/roll-calls [POST]
func RollCall(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RollCallRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RollCallResponse)

	s := service.NewAPIService(ctx)
	currentRoster, actualEventType, err := s.RollCall(&req)
	if err != nil {
		resp.BaseResponse = &common.BaseResponse{
			Code:    constants.CodeFailed,
			Message: err.Error(),
		}
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	// 构造响应消息，包含触发的随机事件信息
	message := "点名成功"
	switch actualEventType {
	case common.RandomEventType_BLESSING_1024:
		message = "点名成功 - 触发【1024福报】！Debug成功！"
	case common.RandomEventType_SOLITUDE_PRIMES:
		message = "点名成功 - 虽是质数，但你不孤独。"
	case common.RandomEventType_LUCKY_7:
		message = "点名成功 - Lucky 7！今日运势大吉！"
	case common.RandomEventType_Double_Point:
		message = "点名成功 - 双倍积分！"
	case common.RandomEventType_CRAZY_THURSDAY:
		message = "点名成功 - 疯狂星期四！"
	}

	resp.BaseResponse = &common.BaseResponse{
		Code:    constants.CodeSuccess,
		Message: message,
	}
	resp.RosterItem = &currentRoster
	resp.ActualEventType = actualEventType // 返回实际生效的事件类型

	c.JSON(consts.StatusOK, resp)
}

// SolveRollCall .
// @router /v1/roll-calls/solve [POST]
func SolveRollCall(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SolveRollCallRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewAPIService(ctx)
	if err := s.SolveRollCall(&req); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "结算成功"

	c.JSON(consts.StatusOK, resp)
}

// ResetRollCall .
// @router /v1/roll-calls/reset [POST]
func ResetRollCall(ctx context.Context, c *app.RequestContext) {
	var err error
	var req struct {
		ClassID string `json:"class_id"`
	}
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.BaseResponse)

	s := service.NewAPIService(ctx)
	if err := s.ResetRollCall(req.ClassID); err != nil {
		resp.Code = constants.CodeFailed
		resp.Message = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Code = constants.CodeSuccess
	resp.Message = "重置成功"

	c.JSON(consts.StatusOK, resp)
}
