// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Class          *class
	Enrollment     *enrollment
	RollCallRecord *rollCallRecord
	ScoreEvent     *scoreEvent
	Student        *student
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Class = &Q.Class
	Enrollment = &Q.Enrollment
	RollCallRecord = &Q.RollCallRecord
	ScoreEvent = &Q.ScoreEvent
	Student = &Q.Student
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Class:          newClass(db, opts...),
		Enrollment:     newEnrollment(db, opts...),
		RollCallRecord: newRollCallRecord(db, opts...),
		ScoreEvent:     newScoreEvent(db, opts...),
		Student:        newStudent(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Class          class
	Enrollment     enrollment
	RollCallRecord rollCallRecord
	ScoreEvent     scoreEvent
	Student        student
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Class:          q.Class.clone(db),
		Enrollment:     q.Enrollment.clone(db),
		RollCallRecord: q.RollCallRecord.clone(db),
		ScoreEvent:     q.ScoreEvent.clone(db),
		Student:        q.Student.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Class:          q.Class.replaceDB(db),
		Enrollment:     q.Enrollment.replaceDB(db),
		RollCallRecord: q.RollCallRecord.replaceDB(db),
		ScoreEvent:     q.ScoreEvent.replaceDB(db),
		Student:        q.Student.replaceDB(db),
	}
}

type queryCtx struct {
	Class          IClassDo
	Enrollment     IEnrollmentDo
	RollCallRecord IRollCallRecordDo
	ScoreEvent     IScoreEventDo
	Student        IStudentDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Class:          q.Class.WithContext(ctx),
		Enrollment:     q.Enrollment.WithContext(ctx),
		RollCallRecord: q.RollCallRecord.WithContext(ctx),
		ScoreEvent:     q.ScoreEvent.WithContext(ctx),
		Student:        q.Student.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
