// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"FZUSENekoCaller/biz/dal/model"
)

func newRollCallRecord(db *gorm.DB, opts ...gen.DOOption) rollCallRecord {
	_rollCallRecord := rollCallRecord{}

	_rollCallRecord.rollCallRecordDo.UseDB(db, opts...)
	_rollCallRecord.rollCallRecordDo.UseModel(&model.RollCallRecord{})

	tableName := _rollCallRecord.rollCallRecordDo.TableName()
	_rollCallRecord.ALL = field.NewAsterisk(tableName)
	_rollCallRecord.RecordID = field.NewString(tableName, "record_id")
	_rollCallRecord.ClassID = field.NewString(tableName, "class_id")
	_rollCallRecord.EnrollmentID = field.NewString(tableName, "enrollment_id")
	_rollCallRecord.StudentID = field.NewString(tableName, "student_id")
	_rollCallRecord.Mode = field.NewInt32(tableName, "mode")
	_rollCallRecord.EventType = field.NewInt32(tableName, "event_type")
	_rollCallRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_rollCallRecord.fillFieldMap()

	return _rollCallRecord
}

type rollCallRecord struct {
	rollCallRecordDo

	ALL          field.Asterisk
	RecordID     field.String
	ClassID      field.String
	EnrollmentID field.String
	StudentID    field.String
	Mode         field.Int32
	EventType    field.Int32
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (r rollCallRecord) Table(newTableName string) *rollCallRecord {
	r.rollCallRecordDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rollCallRecord) As(alias string) *rollCallRecord {
	r.rollCallRecordDo.DO = *(r.rollCallRecordDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rollCallRecord) updateTableName(table string) *rollCallRecord {
	r.ALL = field.NewAsterisk(table)
	r.RecordID = field.NewString(table, "record_id")
	r.ClassID = field.NewString(table, "class_id")
	r.EnrollmentID = field.NewString(table, "enrollment_id")
	r.StudentID = field.NewString(table, "student_id")
	r.Mode = field.NewInt32(table, "mode")
	r.EventType = field.NewInt32(table, "event_type")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *rollCallRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rollCallRecord) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["record_id"] = r.RecordID
	r.fieldMap["class_id"] = r.ClassID
	r.fieldMap["enrollment_id"] = r.EnrollmentID
	r.fieldMap["student_id"] = r.StudentID
	r.fieldMap["mode"] = r.Mode
	r.fieldMap["event_type"] = r.EventType
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r rollCallRecord) clone(db *gorm.DB) rollCallRecord {
	r.rollCallRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rollCallRecord) replaceDB(db *gorm.DB) rollCallRecord {
	r.rollCallRecordDo.ReplaceDB(db)
	return r
}

type rollCallRecordDo struct{ gen.DO }

type IRollCallRecordDo interface {
	gen.SubQuery
	Debug() IRollCallRecordDo
	WithContext(ctx context.Context) IRollCallRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRollCallRecordDo
	WriteDB() IRollCallRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRollCallRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRollCallRecordDo
	Not(conds ...gen.Condition) IRollCallRecordDo
	Or(conds ...gen.Condition) IRollCallRecordDo
	Select(conds ...field.Expr) IRollCallRecordDo
	Where(conds ...gen.Condition) IRollCallRecordDo
	Order(conds ...field.Expr) IRollCallRecordDo
	Distinct(cols ...field.Expr) IRollCallRecordDo
	Omit(cols ...field.Expr) IRollCallRecordDo
	Join(table schema.Tabler, on ...field.Expr) IRollCallRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRollCallRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRollCallRecordDo
	Group(cols ...field.Expr) IRollCallRecordDo
	Having(conds ...gen.Condition) IRollCallRecordDo
	Limit(limit int) IRollCallRecordDo
	Offset(offset int) IRollCallRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRollCallRecordDo
	Unscoped() IRollCallRecordDo
	Create(values ...*model.RollCallRecord) error
	CreateInBatches(values []*model.RollCallRecord, batchSize int) error
	Save(values ...*model.RollCallRecord) error
	First() (*model.RollCallRecord, error)
	Take() (*model.RollCallRecord, error)
	Last() (*model.RollCallRecord, error)
	Find() ([]*model.RollCallRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RollCallRecord, err error)
	FindInBatches(result *[]*model.RollCallRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RollCallRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRollCallRecordDo
	Assign(attrs ...field.AssignExpr) IRollCallRecordDo
	Joins(fields ...field.RelationField) IRollCallRecordDo
	Preload(fields ...field.RelationField) IRollCallRecordDo
	FirstOrInit() (*model.RollCallRecord, error)
	FirstOrCreate() (*model.RollCallRecord, error)
	FindByPage(offset int, limit int) (result []*model.RollCallRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRollCallRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rollCallRecordDo) Debug() IRollCallRecordDo {
	return r.withDO(r.DO.Debug())
}

func (r rollCallRecordDo) WithContext(ctx context.Context) IRollCallRecordDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rollCallRecordDo) ReadDB() IRollCallRecordDo {
	return r.Clauses(dbresolver.Read)
}

func (r rollCallRecordDo) WriteDB() IRollCallRecordDo {
	return r.Clauses(dbresolver.Write)
}

func (r rollCallRecordDo) Session(config *gorm.Session) IRollCallRecordDo {
	return r.withDO(r.DO.Session(config))
}

func (r rollCallRecordDo) Clauses(conds ...clause.Expression) IRollCallRecordDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rollCallRecordDo) Returning(value interface{}, columns ...string) IRollCallRecordDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rollCallRecordDo) Not(conds ...gen.Condition) IRollCallRecordDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rollCallRecordDo) Or(conds ...gen.Condition) IRollCallRecordDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rollCallRecordDo) Select(conds ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rollCallRecordDo) Where(conds ...gen.Condition) IRollCallRecordDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rollCallRecordDo) Order(conds ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rollCallRecordDo) Distinct(cols ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rollCallRecordDo) Omit(cols ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rollCallRecordDo) Join(table schema.Tabler, on ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rollCallRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rollCallRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rollCallRecordDo) Group(cols ...field.Expr) IRollCallRecordDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rollCallRecordDo) Having(conds ...gen.Condition) IRollCallRecordDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rollCallRecordDo) Limit(limit int) IRollCallRecordDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rollCallRecordDo) Offset(offset int) IRollCallRecordDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rollCallRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRollCallRecordDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rollCallRecordDo) Unscoped() IRollCallRecordDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rollCallRecordDo) Create(values ...*model.RollCallRecord) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rollCallRecordDo) CreateInBatches(values []*model.RollCallRecord, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rollCallRecordDo) Save(values ...*model.RollCallRecord) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rollCallRecordDo) First() (*model.RollCallRecord, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RollCallRecord), nil
	}
}

func (r rollCallRecordDo) Take() (*model.RollCallRecord, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RollCallRecord), nil
	}
}

func (r rollCallRecordDo) Last() (*model.RollCallRecord, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RollCallRecord), nil
	}
}

func (r rollCallRecordDo) Find() ([]*model.RollCallRecord, error) {
	result, err := r.DO.Find()
	return result.([]*model.RollCallRecord), err
}

func (r rollCallRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RollCallRecord, err error) {
	buf := make([]*model.RollCallRecord, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rollCallRecordDo) FindInBatches(result *[]*model.RollCallRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rollCallRecordDo) Attrs(attrs ...field.AssignExpr) IRollCallRecordDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rollCallRecordDo) Assign(attrs ...field.AssignExpr) IRollCallRecordDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rollCallRecordDo) Joins(fields ...field.RelationField) IRollCallRecordDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rollCallRecordDo) Preload(fields ...field.RelationField) IRollCallRecordDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rollCallRecordDo) FirstOrInit() (*model.RollCallRecord, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RollCallRecord), nil
	}
}

func (r rollCallRecordDo) FirstOrCreate() (*model.RollCallRecord, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RollCallRecord), nil
	}
}

func (r rollCallRecordDo) FindByPage(offset int, limit int) (result []*model.RollCallRecord, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rollCallRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rollCallRecordDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rollCallRecordDo) Delete(models ...*model.RollCallRecord) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rollCallRecordDo) withDO(do gen.Dao) *rollCallRecordDo {
	r.DO = *do.(*gen.DO)
	return r
}
