// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"FZUSENekoCaller/biz/dal/model"
)

func newScoreEvent(db *gorm.DB, opts ...gen.DOOption) scoreEvent {
	_scoreEvent := scoreEvent{}

	_scoreEvent.scoreEventDo.UseDB(db, opts...)
	_scoreEvent.scoreEventDo.UseModel(&model.ScoreEvent{})

	tableName := _scoreEvent.scoreEventDo.TableName()
	_scoreEvent.ALL = field.NewAsterisk(tableName)
	_scoreEvent.EventID = field.NewString(tableName, "event_id")
	_scoreEvent.EnrollmentID = field.NewString(tableName, "enrollment_id")
	_scoreEvent.StudentID = field.NewString(tableName, "student_id")
	_scoreEvent.ClassID = field.NewString(tableName, "class_id")
	_scoreEvent.Delta = field.NewFloat64(tableName, "delta")
	_scoreEvent.Reason = field.NewString(tableName, "reason")
	_scoreEvent.EventType = field.NewInt32(tableName, "event_type")
	_scoreEvent.Metadata = field.NewField(tableName, "metadata")
	_scoreEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_scoreEvent.fillFieldMap()

	return _scoreEvent
}

type scoreEvent struct {
	scoreEventDo

	ALL          field.Asterisk
	EventID      field.String
	EnrollmentID field.String
	StudentID    field.String
	ClassID      field.String
	Delta        field.Float64
	Reason       field.String
	EventType    field.Int32
	Metadata     field.Field
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (s scoreEvent) Table(newTableName string) *scoreEvent {
	s.scoreEventDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scoreEvent) As(alias string) *scoreEvent {
	s.scoreEventDo.DO = *(s.scoreEventDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scoreEvent) updateTableName(table string) *scoreEvent {
	s.ALL = field.NewAsterisk(table)
	s.EventID = field.NewString(table, "event_id")
	s.EnrollmentID = field.NewString(table, "enrollment_id")
	s.StudentID = field.NewString(table, "student_id")
	s.ClassID = field.NewString(table, "class_id")
	s.Delta = field.NewFloat64(table, "delta")
	s.Reason = field.NewString(table, "reason")
	s.EventType = field.NewInt32(table, "event_type")
	s.Metadata = field.NewField(table, "metadata")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *scoreEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scoreEvent) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["event_id"] = s.EventID
	s.fieldMap["enrollment_id"] = s.EnrollmentID
	s.fieldMap["student_id"] = s.StudentID
	s.fieldMap["class_id"] = s.ClassID
	s.fieldMap["delta"] = s.Delta
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["event_type"] = s.EventType
	s.fieldMap["metadata"] = s.Metadata
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s scoreEvent) clone(db *gorm.DB) scoreEvent {
	s.scoreEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s scoreEvent) replaceDB(db *gorm.DB) scoreEvent {
	s.scoreEventDo.ReplaceDB(db)
	return s
}

type scoreEventDo struct{ gen.DO }

type IScoreEventDo interface {
	gen.SubQuery
	Debug() IScoreEventDo
	WithContext(ctx context.Context) IScoreEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IScoreEventDo
	WriteDB() IScoreEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IScoreEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IScoreEventDo
	Not(conds ...gen.Condition) IScoreEventDo
	Or(conds ...gen.Condition) IScoreEventDo
	Select(conds ...field.Expr) IScoreEventDo
	Where(conds ...gen.Condition) IScoreEventDo
	Order(conds ...field.Expr) IScoreEventDo
	Distinct(cols ...field.Expr) IScoreEventDo
	Omit(cols ...field.Expr) IScoreEventDo
	Join(table schema.Tabler, on ...field.Expr) IScoreEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IScoreEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IScoreEventDo
	Group(cols ...field.Expr) IScoreEventDo
	Having(conds ...gen.Condition) IScoreEventDo
	Limit(limit int) IScoreEventDo
	Offset(offset int) IScoreEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IScoreEventDo
	Unscoped() IScoreEventDo
	Create(values ...*model.ScoreEvent) error
	CreateInBatches(values []*model.ScoreEvent, batchSize int) error
	Save(values ...*model.ScoreEvent) error
	First() (*model.ScoreEvent, error)
	Take() (*model.ScoreEvent, error)
	Last() (*model.ScoreEvent, error)
	Find() ([]*model.ScoreEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ScoreEvent, err error)
	FindInBatches(result *[]*model.ScoreEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ScoreEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IScoreEventDo
	Assign(attrs ...field.AssignExpr) IScoreEventDo
	Joins(fields ...field.RelationField) IScoreEventDo
	Preload(fields ...field.RelationField) IScoreEventDo
	FirstOrInit() (*model.ScoreEvent, error)
	FirstOrCreate() (*model.ScoreEvent, error)
	FindByPage(offset int, limit int) (result []*model.ScoreEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IScoreEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s scoreEventDo) Debug() IScoreEventDo {
	return s.withDO(s.DO.Debug())
}

func (s scoreEventDo) WithContext(ctx context.Context) IScoreEventDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scoreEventDo) ReadDB() IScoreEventDo {
	return s.Clauses(dbresolver.Read)
}

func (s scoreEventDo) WriteDB() IScoreEventDo {
	return s.Clauses(dbresolver.Write)
}

func (s scoreEventDo) Session(config *gorm.Session) IScoreEventDo {
	return s.withDO(s.DO.Session(config))
}

func (s scoreEventDo) Clauses(conds ...clause.Expression) IScoreEventDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scoreEventDo) Returning(value interface{}, columns ...string) IScoreEventDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scoreEventDo) Not(conds ...gen.Condition) IScoreEventDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scoreEventDo) Or(conds ...gen.Condition) IScoreEventDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scoreEventDo) Select(conds ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scoreEventDo) Where(conds ...gen.Condition) IScoreEventDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scoreEventDo) Order(conds ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scoreEventDo) Distinct(cols ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scoreEventDo) Omit(cols ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scoreEventDo) Join(table schema.Tabler, on ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scoreEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scoreEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scoreEventDo) Group(cols ...field.Expr) IScoreEventDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scoreEventDo) Having(conds ...gen.Condition) IScoreEventDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scoreEventDo) Limit(limit int) IScoreEventDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scoreEventDo) Offset(offset int) IScoreEventDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scoreEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IScoreEventDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scoreEventDo) Unscoped() IScoreEventDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scoreEventDo) Create(values ...*model.ScoreEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scoreEventDo) CreateInBatches(values []*model.ScoreEvent, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scoreEventDo) Save(values ...*model.ScoreEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scoreEventDo) First() (*model.ScoreEvent, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScoreEvent), nil
	}
}

func (s scoreEventDo) Take() (*model.ScoreEvent, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScoreEvent), nil
	}
}

func (s scoreEventDo) Last() (*model.ScoreEvent, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScoreEvent), nil
	}
}

func (s scoreEventDo) Find() ([]*model.ScoreEvent, error) {
	result, err := s.DO.Find()
	return result.([]*model.ScoreEvent), err
}

func (s scoreEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ScoreEvent, err error) {
	buf := make([]*model.ScoreEvent, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scoreEventDo) FindInBatches(result *[]*model.ScoreEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scoreEventDo) Attrs(attrs ...field.AssignExpr) IScoreEventDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scoreEventDo) Assign(attrs ...field.AssignExpr) IScoreEventDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scoreEventDo) Joins(fields ...field.RelationField) IScoreEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scoreEventDo) Preload(fields ...field.RelationField) IScoreEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scoreEventDo) FirstOrInit() (*model.ScoreEvent, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScoreEvent), nil
	}
}

func (s scoreEventDo) FirstOrCreate() (*model.ScoreEvent, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScoreEvent), nil
	}
}

func (s scoreEventDo) FindByPage(offset int, limit int) (result []*model.ScoreEvent, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scoreEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scoreEventDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scoreEventDo) Delete(models ...*model.ScoreEvent) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scoreEventDo) withDO(do gen.Dao) *scoreEventDo {
	s.DO = *do.(*gen.DO)
	return s
}
